/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIASRStatus.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Farsava {

OAIASRStatus::OAIASRStatus(QString json) {
    this->init();
    this->fromJson(json);
}

OAIASRStatus::OAIASRStatus() {
    this->init();
}

OAIASRStatus::~OAIASRStatus() {

}

void
OAIASRStatus::init() {
    
    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIASRStatus::INVALID_VALUE_OPENAPI_GENERATED;
}

void
OAIASRStatus::fromJson(QString jsonString) {
     
    if ( jsonString.compare("queued", Qt::CaseInsensitive) == 0) {
        m_value = eOAIASRStatus::QUEUED;
        m_value_isValid = true;
    } 
    else if ( jsonString.compare("processing", Qt::CaseInsensitive) == 0) {
        m_value = eOAIASRStatus::PROCESSING;
        m_value_isValid = true;
    } 
    else if ( jsonString.compare("done", Qt::CaseInsensitive) == 0) {
        m_value = eOAIASRStatus::DONE;
        m_value_isValid = true;
    } 
    else if ( jsonString.compare("partial", Qt::CaseInsensitive) == 0) {
        m_value = eOAIASRStatus::PARTIAL;
        m_value_isValid = true;
    }
}

void
OAIASRStatus::fromJsonValue(QJsonValue json) {
    
    fromJson(json.toString());
}

QString
OAIASRStatus::asJson () const {
    
    QString val;
    switch (m_value){
        case eOAIASRStatus::QUEUED:
            val = "queued";
            break;
        case eOAIASRStatus::PROCESSING:
            val = "processing";
            break;
        case eOAIASRStatus::DONE:
            val = "done";
            break;
        case eOAIASRStatus::PARTIAL:
            val = "partial";
            break; 
        default:
            break;
    }
    return val;
}

QJsonValue
OAIASRStatus::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIASRStatus::eOAIASRStatus OAIASRStatus::getValue() const {
    return m_value;
}

void OAIASRStatus::setValue(const OAIASRStatus::eOAIASRStatus& value){
    m_value = value;
    m_value_isSet = true;
}
bool
OAIASRStatus::isSet() const {
    
    return m_value_isSet;
}

bool
OAIASRStatus::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

}

