/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIASRResponseBody.h
 *
 * 
 */

#ifndef OAIASRResponseBody_H
#define OAIASRResponseBody_H

#include <QJsonObject>


#include "farsava_model/OAIASRStatus.h"
#include "farsava_model/OAISpeechRecognitionResult.h"
#include <QList>
#include <QString>

#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAIASRResponseBody: public OAIObject {
public:
    OAIASRResponseBody();
    OAIASRResponseBody(QString json);
    ~OAIASRResponseBody() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    QString getTranscriptionId() const;
    void setTranscriptionId(const QString &transcription_id);

    
    double getDuration() const;
    void setDuration(const double &duration);

    
    double getInferenceTime() const;
    void setInferenceTime(const double &inference_time);

    
    OAIASRStatus getStatus() const;
    void setStatus(const OAIASRStatus &status);

    
    QList<OAISpeechRecognitionResult> getResults() const;
    void setResults(const QList<OAISpeechRecognitionResult> &results);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    QString transcription_id;
    bool m_transcription_id_isSet;
    bool m_transcription_id_isValid;
    
    double duration;
    bool m_duration_isSet;
    bool m_duration_isValid;
    
    double inference_time;
    bool m_inference_time_isSet;
    bool m_inference_time_isValid;
    
    OAIASRStatus status;
    bool m_status_isSet;
    bool m_status_isValid;
    
    QList<OAISpeechRecognitionResult> results;
    bool m_results_isSet;
    bool m_results_isValid;
    
    };

}

#endif // OAIASRResponseBody_H
