/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAudioEncoding.h
 *
 * Encoding of audio data sent in all RecognitionAudio messages. In case of voice synthesize, this is the format of the requested audio byte stream. This field is required for all audio formats. 
 */

#ifndef OAIAudioEncoding_H
#define OAIAudioEncoding_H

#include <QJsonObject>



#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAIAudioEncoding: public OAIEnum {
public:
    OAIAudioEncoding();
    OAIAudioEncoding(QString json);
    ~OAIAudioEncoding() override;

    QString asJson () const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    
    enum class eOAIAudioEncoding {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        LINEAR16, 
        FLAC, 
        MP3
    };

    OAIAudioEncoding::eOAIAudioEncoding getValue() const;
    void setValue(const OAIAudioEncoding::eOAIAudioEncoding& value);
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    eOAIAudioEncoding m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

}

#endif // OAIAudioEncoding_H
