/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIASRRequestBodyData.h
 *
 * 
 */

#ifndef OAIASRRequestBodyData_H
#define OAIASRRequestBodyData_H

#include <QJsonObject>


#include "farsava_model/OAIRecognitionAudioData.h"
#include "farsava_model/OAIRecognitionConfig.h"

#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAIASRRequestBodyData: public OAIObject {
public:
    OAIASRRequestBodyData();
    OAIASRRequestBodyData(QString json);
    ~OAIASRRequestBodyData() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    OAIRecognitionConfig getConfig() const;
    void setConfig(const OAIRecognitionConfig &config);

    
    OAIRecognitionAudioData getAudio() const;
    void setAudio(const OAIRecognitionAudioData &audio);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    OAIRecognitionConfig config;
    bool m_config_isSet;
    bool m_config_isValid;
    
    OAIRecognitionAudioData audio;
    bool m_audio_isSet;
    bool m_audio_isValid;
    
    };

}

#endif // OAIASRRequestBodyData_H
