/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIError.h
 *
 * 
 */

#ifndef OAIError_H
#define OAIError_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAIError: public OAIObject {
public:
    OAIError();
    OAIError(QString json);
    ~OAIError() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    QString getStatus() const;
    void setStatus(const QString &status);

    
    QString getDetail() const;
    void setDetail(const QString &detail);

    
    QString getTitle() const;
    void setTitle(const QString &title);

    
    QString getType() const;
    void setType(const QString &type);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    QString status;
    bool m_status_isSet;
    bool m_status_isValid;
    
    QString detail;
    bool m_detail_isSet;
    bool m_detail_isValid;
    
    QString title;
    bool m_title_isSet;
    bool m_title_isValid;
    
    QString type;
    bool m_type_isSet;
    bool m_type_isValid;
    
    };

}

#endif // OAIError_H
