/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIHealthCheckResponseBody.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Farsava {

OAIHealthCheckResponseBody::OAIHealthCheckResponseBody(QString json) {
    this->init();
    this->fromJson(json);
}

OAIHealthCheckResponseBody::OAIHealthCheckResponseBody() {
    this->init();
}

OAIHealthCheckResponseBody::~OAIHealthCheckResponseBody() {

}

void
OAIHealthCheckResponseBody::init() {
    
    m_status_isSet = false;
    m_status_isValid = false;
    
    m_message_isSet = false;
    m_message_isValid = false;
    
    m_version_isSet = false;
    m_version_isValid = false;
    }

void
OAIHealthCheckResponseBody::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAIHealthCheckResponseBody::fromJsonObject(QJsonObject json) {
    
    m_status_isValid = ::Farsava::fromJsonValue(status, json[QString("status")]);
    
    
    m_message_isValid = ::Farsava::fromJsonValue(message, json[QString("message")]);
    
    
    m_version_isValid = ::Farsava::fromJsonValue(version, json[QString("version")]);
    
    
}

QString
OAIHealthCheckResponseBody::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIHealthCheckResponseBody::asJsonObject() const {
    QJsonObject obj;
	if(m_status_isSet){
        obj.insert(QString("status"), ::Farsava::toJsonValue(status));
    }
	if(m_message_isSet){
        obj.insert(QString("message"), ::Farsava::toJsonValue(message));
    }
	if(m_version_isSet){
        obj.insert(QString("version"), ::Farsava::toJsonValue(version));
    }
    return obj;
}


QString
OAIHealthCheckResponseBody::getStatus() const {
    return status;
}
void
OAIHealthCheckResponseBody::setStatus(const QString &status) {
    this->status = status;
    this->m_status_isSet = true;
}


QString
OAIHealthCheckResponseBody::getMessage() const {
    return message;
}
void
OAIHealthCheckResponseBody::setMessage(const QString &message) {
    this->message = message;
    this->m_message_isSet = true;
}


QString
OAIHealthCheckResponseBody::getVersion() const {
    return version;
}
void
OAIHealthCheckResponseBody::setVersion(const QString &version) {
    this->version = version;
    this->m_version_isSet = true;
}

bool
OAIHealthCheckResponseBody::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(m_status_isSet){ isObjectUpdated = true; break;}
    
        if(m_message_isSet){ isObjectUpdated = true; break;}
    
        if(m_version_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAIHealthCheckResponseBody::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

}

