/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILMStatus.h
 *
 * Status of the language model training process. After a language model training finishes it can be used for speech recognition using its languageModelId. 
 */

#ifndef OAILMStatus_H
#define OAILMStatus_H

#include <QJsonObject>



#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAILMStatus: public OAIEnum {
public:
    OAILMStatus();
    OAILMStatus(QString json);
    ~OAILMStatus() override;

    QString asJson () const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    
    enum class eOAILMStatus {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        QUEUED, 
        TRAINING, 
        TRAINED
    };

    OAILMStatus::eOAILMStatus getValue() const;
    void setValue(const OAILMStatus::eOAILMStatus& value);
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    eOAILMStatus m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

}

#endif // OAILMStatus_H
