/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILanguageCode.h
 *
 * The language of the supplied audio as a language tag. Example **en** for english language. See Language Support for a list of the currently supported language codes. 
 */

#ifndef OAILanguageCode_H
#define OAILanguageCode_H

#include <QJsonObject>



#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAILanguageCode: public OAIEnum {
public:
    OAILanguageCode();
    OAILanguageCode(QString json);
    ~OAILanguageCode() override;

    QString asJson () const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    
    enum class eOAILanguageCode {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        FA, 
        EN
    };

    OAILanguageCode::eOAILanguageCode getValue() const;
    void setValue(const OAILanguageCode::eOAILanguageCode& value);
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    eOAILanguageCode m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

}

#endif // OAILanguageCode_H
