/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAILMStatus.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Farsava {

OAILMStatus::OAILMStatus(QString json) {
    this->init();
    this->fromJson(json);
}

OAILMStatus::OAILMStatus() {
    this->init();
}

OAILMStatus::~OAILMStatus() {

}

void
OAILMStatus::init() {
    
    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAILMStatus::INVALID_VALUE_OPENAPI_GENERATED;
}

void
OAILMStatus::fromJson(QString jsonString) {
     
    if ( jsonString.compare("queued", Qt::CaseInsensitive) == 0) {
        m_value = eOAILMStatus::QUEUED;
        m_value_isValid = true;
    } 
    else if ( jsonString.compare("training", Qt::CaseInsensitive) == 0) {
        m_value = eOAILMStatus::TRAINING;
        m_value_isValid = true;
    } 
    else if ( jsonString.compare("trained", Qt::CaseInsensitive) == 0) {
        m_value = eOAILMStatus::TRAINED;
        m_value_isValid = true;
    }
}

void
OAILMStatus::fromJsonValue(QJsonValue json) {
    
    fromJson(json.toString());
}

QString
OAILMStatus::asJson () const {
    
    QString val;
    switch (m_value){
        case eOAILMStatus::QUEUED:
            val = "queued";
            break;
        case eOAILMStatus::TRAINING:
            val = "training";
            break;
        case eOAILMStatus::TRAINED:
            val = "trained";
            break; 
        default:
            break;
    }
    return val;
}

QJsonValue
OAILMStatus::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAILMStatus::eOAILMStatus OAILMStatus::getValue() const {
    return m_value;
}

void OAILMStatus::setValue(const OAILMStatus::eOAILMStatus& value){
    m_value = value;
    m_value_isSet = true;
}
bool
OAILMStatus::isSet() const {
    
    return m_value_isSet;
}

bool
OAILMStatus::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

}

