/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILanguageModelResult.h
 *
 * 
 */

#ifndef OAILanguageModelResult_H
#define OAILanguageModelResult_H

#include <QJsonObject>


#include "farsava_model/OAILMStatus.h"
#include <QString>

#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAILanguageModelResult: public OAIObject {
public:
    OAILanguageModelResult();
    OAILanguageModelResult(QString json);
    ~OAILanguageModelResult() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    QString getLanguageModelId() const;
    void setLanguageModelId(const QString &language_model_id);

    
    QString getName() const;
    void setName(const QString &name);

    
    OAILMStatus getStatus() const;
    void setStatus(const OAILMStatus &status);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    QString language_model_id;
    bool m_language_model_id_isSet;
    bool m_language_model_id_isValid;
    
    QString name;
    bool m_name_isSet;
    bool m_name_isValid;
    
    OAILMStatus status;
    bool m_status_isSet;
    bool m_status_isValid;
    
    };

}

#endif // OAILanguageModelResult_H
