/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAILanguageCode.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Farsava {

OAILanguageCode::OAILanguageCode(QString json) {
    this->init();
    this->fromJson(json);
}

OAILanguageCode::OAILanguageCode() {
    this->init();
}

OAILanguageCode::~OAILanguageCode() {

}

void
OAILanguageCode::init() {
    
    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAILanguageCode::INVALID_VALUE_OPENAPI_GENERATED;
}

void
OAILanguageCode::fromJson(QString jsonString) {
     
    if ( jsonString.compare("fa", Qt::CaseInsensitive) == 0) {
        m_value = eOAILanguageCode::FA;
        m_value_isValid = true;
    } 
    else if ( jsonString.compare("en", Qt::CaseInsensitive) == 0) {
        m_value = eOAILanguageCode::EN;
        m_value_isValid = true;
    }
}

void
OAILanguageCode::fromJsonValue(QJsonValue json) {
    
    fromJson(json.toString());
}

QString
OAILanguageCode::asJson () const {
    
    QString val;
    switch (m_value){
        case eOAILanguageCode::FA:
            val = "fa";
            break;
        case eOAILanguageCode::EN:
            val = "en";
            break; 
        default:
            break;
    }
    return val;
}

QJsonValue
OAILanguageCode::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAILanguageCode::eOAILanguageCode OAILanguageCode::getValue() const {
    return m_value;
}

void OAILanguageCode::setValue(const OAILanguageCode::eOAILanguageCode& value){
    m_value = value;
    m_value_isSet = true;
}
bool
OAILanguageCode::isSet() const {
    
    return m_value_isSet;
}

bool
OAILanguageCode::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

}

