/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIRecognitionAudioData.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Farsava {

OAIRecognitionAudioData::OAIRecognitionAudioData(QString json) {
    this->init();
    this->fromJson(json);
}

OAIRecognitionAudioData::OAIRecognitionAudioData() {
    this->init();
}

OAIRecognitionAudioData::~OAIRecognitionAudioData() {

}

void
OAIRecognitionAudioData::init() {
    
    m_data_isSet = false;
    m_data_isValid = false;
    }

void
OAIRecognitionAudioData::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAIRecognitionAudioData::fromJsonObject(QJsonObject json) {
    
    m_data_isValid = ::Farsava::fromJsonValue(data, json[QString("data")]);
    
    
}

QString
OAIRecognitionAudioData::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIRecognitionAudioData::asJsonObject() const {
    QJsonObject obj;
	if(m_data_isSet){
        obj.insert(QString("data"), ::Farsava::toJsonValue(data));
    }
    return obj;
}


QByteArray
OAIRecognitionAudioData::getData() const {
    return data;
}
void
OAIRecognitionAudioData::setData(const QByteArray &data) {
    this->data = data;
    this->m_data_isSet = true;
}

bool
OAIRecognitionAudioData::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(m_data_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAIRecognitionAudioData::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_data_isValid && true;
}

}

