/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAISynthesisInput.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Farsava {

OAISynthesisInput::OAISynthesisInput(QString json) {
    this->init();
    this->fromJson(json);
}

OAISynthesisInput::OAISynthesisInput() {
    this->init();
}

OAISynthesisInput::~OAISynthesisInput() {

}

void
OAISynthesisInput::init() {
    
    m_text_isSet = false;
    m_text_isValid = false;
    
    m_ssml_isSet = false;
    m_ssml_isValid = false;
    }

void
OAISynthesisInput::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAISynthesisInput::fromJsonObject(QJsonObject json) {
    
    m_text_isValid = ::Farsava::fromJsonValue(text, json[QString("text")]);
    
    
    m_ssml_isValid = ::Farsava::fromJsonValue(ssml, json[QString("ssml")]);
    
    
}

QString
OAISynthesisInput::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAISynthesisInput::asJsonObject() const {
    QJsonObject obj;
	if(m_text_isSet){
        obj.insert(QString("text"), ::Farsava::toJsonValue(text));
    }
	if(m_ssml_isSet){
        obj.insert(QString("ssml"), ::Farsava::toJsonValue(ssml));
    }
    return obj;
}


QString
OAISynthesisInput::getText() const {
    return text;
}
void
OAISynthesisInput::setText(const QString &text) {
    this->text = text;
    this->m_text_isSet = true;
}


QString
OAISynthesisInput::getSsml() const {
    return ssml;
}
void
OAISynthesisInput::setSsml(const QString &ssml) {
    this->ssml = ssml;
    this->m_ssml_isSet = true;
}

bool
OAISynthesisInput::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(m_text_isSet){ isObjectUpdated = true; break;}
    
        if(m_ssml_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAISynthesisInput::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

}

