/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAISpeechRecognitionModel.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Farsava {

OAISpeechRecognitionModel::OAISpeechRecognitionModel(QString json) {
    this->init();
    this->fromJson(json);
}

OAISpeechRecognitionModel::OAISpeechRecognitionModel() {
    this->init();
}

OAISpeechRecognitionModel::~OAISpeechRecognitionModel() {

}

void
OAISpeechRecognitionModel::init() {
    
    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAISpeechRecognitionModel::INVALID_VALUE_OPENAPI_GENERATED;
}

void
OAISpeechRecognitionModel::fromJson(QString jsonString) {
     
    if ( jsonString.compare("default", Qt::CaseInsensitive) == 0) {
        m_value = eOAISpeechRecognitionModel::DEFAULT;
        m_value_isValid = true;
    } 
    else if ( jsonString.compare("video", Qt::CaseInsensitive) == 0) {
        m_value = eOAISpeechRecognitionModel::VIDEO;
        m_value_isValid = true;
    } 
    else if ( jsonString.compare("command_and_search", Qt::CaseInsensitive) == 0) {
        m_value = eOAISpeechRecognitionModel::COMMAND_AND_SEARCH;
        m_value_isValid = true;
    } 
    else if ( jsonString.compare("phone_call", Qt::CaseInsensitive) == 0) {
        m_value = eOAISpeechRecognitionModel::PHONE_CALL;
        m_value_isValid = true;
    }
}

void
OAISpeechRecognitionModel::fromJsonValue(QJsonValue json) {
    
    fromJson(json.toString());
}

QString
OAISpeechRecognitionModel::asJson () const {
    
    QString val;
    switch (m_value){
        case eOAISpeechRecognitionModel::DEFAULT:
            val = "default";
            break;
        case eOAISpeechRecognitionModel::VIDEO:
            val = "video";
            break;
        case eOAISpeechRecognitionModel::COMMAND_AND_SEARCH:
            val = "command_and_search";
            break;
        case eOAISpeechRecognitionModel::PHONE_CALL:
            val = "phone_call";
            break; 
        default:
            break;
    }
    return val;
}

QJsonValue
OAISpeechRecognitionModel::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAISpeechRecognitionModel::eOAISpeechRecognitionModel OAISpeechRecognitionModel::getValue() const {
    return m_value;
}

void OAISpeechRecognitionModel::setValue(const OAISpeechRecognitionModel::eOAISpeechRecognitionModel& value){
    m_value = value;
    m_value_isSet = true;
}
bool
OAISpeechRecognitionModel::isSet() const {
    
    return m_value_isSet;
}

bool
OAISpeechRecognitionModel::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

}

