/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISpeechRecognitionResult.h
 *
 * 
 */

#ifndef OAISpeechRecognitionResult_H
#define OAISpeechRecognitionResult_H

#include <QJsonObject>


#include "farsava_model/OAIWordInfo.h"
#include <QList>
#include <QString>

#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAISpeechRecognitionResult: public OAIObject {
public:
    OAISpeechRecognitionResult();
    OAISpeechRecognitionResult(QString json);
    ~OAISpeechRecognitionResult() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    QString getTranscript() const;
    void setTranscript(const QString &transcript);

    
    double getConfidence() const;
    void setConfidence(const double &confidence);

    
    QList<OAIWordInfo> getWords() const;
    void setWords(const QList<OAIWordInfo> &words);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    QString transcript;
    bool m_transcript_isSet;
    bool m_transcript_isValid;
    
    double confidence;
    bool m_confidence_isSet;
    bool m_confidence_isValid;
    
    QList<OAIWordInfo> words;
    bool m_words_isSet;
    bool m_words_isValid;
    
    };

}

#endif // OAISpeechRecognitionResult_H
