/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISynthesisInput.h
 *
 * The Synthesizer requires either plain text or SSML as input. Only provide text OR ssml. Providing both will result in a bad request response.
 */

#ifndef OAISynthesisInput_H
#define OAISynthesisInput_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAISynthesisInput: public OAIObject {
public:
    OAISynthesisInput();
    OAISynthesisInput(QString json);
    ~OAISynthesisInput() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    QString getText() const;
    void setText(const QString &text);

    
    QString getSsml() const;
    void setSsml(const QString &ssml);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    QString text;
    bool m_text_isSet;
    bool m_text_isValid;
    
    QString ssml;
    bool m_ssml_isSet;
    bool m_ssml_isValid;
    
    };

}

#endif // OAISynthesisInput_H
