/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAITTSRequestBody.h
 *
 * 
 */

#ifndef OAITTSRequestBody_H
#define OAITTSRequestBody_H

#include <QJsonObject>


#include "farsava_model/OAISynthesisInput.h"
#include "farsava_model/OAITTSAudioConfig.h"
#include "farsava_model/OAIVoiceSelectionParams.h"

#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAITTSRequestBody: public OAIObject {
public:
    OAITTSRequestBody();
    OAITTSRequestBody(QString json);
    ~OAITTSRequestBody() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    OAISynthesisInput getSynthesisInput() const;
    void setSynthesisInput(const OAISynthesisInput &synthesis_input);

    
    OAIVoiceSelectionParams getVoiceConfig() const;
    void setVoiceConfig(const OAIVoiceSelectionParams &voice_config);

    
    OAITTSAudioConfig getAudioConfig() const;
    void setAudioConfig(const OAITTSAudioConfig &audio_config);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    OAISynthesisInput synthesis_input;
    bool m_synthesis_input_isSet;
    bool m_synthesis_input_isValid;
    
    OAIVoiceSelectionParams voice_config;
    bool m_voice_config_isSet;
    bool m_voice_config_isValid;
    
    OAITTSAudioConfig audio_config;
    bool m_audio_config_isSet;
    bool m_audio_config_isValid;
    
    };

}

#endif // OAITTSRequestBody_H
