/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAITTSResponseBody.h
 *
 * 
 */

#ifndef OAITTSResponseBody_H
#define OAITTSResponseBody_H

#include <QJsonObject>


#include <QByteArray>

#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAITTSResponseBody: public OAIObject {
public:
    OAITTSResponseBody();
    OAITTSResponseBody(QString json);
    ~OAITTSResponseBody() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    QByteArray getAudioContent() const;
    void setAudioContent(const QByteArray &audio_content);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    QByteArray audio_content;
    bool m_audio_content_isSet;
    bool m_audio_content_isValid;
    
    };

}

#endif // OAITTSResponseBody_H
