/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAITTSAudioConfig.h
 *
 * The configuration of the synthesized audio.
 */

#ifndef OAITTSAudioConfig_H
#define OAITTSAudioConfig_H

#include <QJsonObject>


#include "farsava_model/OAIAudioEncoding.h"
#include "farsava_model/OAINumber.h"

#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAITTSAudioConfig: public OAIObject {
public:
    OAITTSAudioConfig();
    OAITTSAudioConfig(QString json);
    ~OAITTSAudioConfig() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    OAIAudioEncoding getAudioEncoding() const;
    void setAudioEncoding(const OAIAudioEncoding &audio_encoding);

    
    qint32 getSampleRateHertz() const;
    void setSampleRateHertz(const qint32 &sample_rate_hertz);

    
    OAINumber getSpeakingRate() const;
    void setSpeakingRate(const OAINumber &speaking_rate);

    
    OAINumber getPitch() const;
    void setPitch(const OAINumber &pitch);

    
    OAINumber getVolumeGainDb() const;
    void setVolumeGainDb(const OAINumber &volume_gain_db);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    OAIAudioEncoding audio_encoding;
    bool m_audio_encoding_isSet;
    bool m_audio_encoding_isValid;
    
    qint32 sample_rate_hertz;
    bool m_sample_rate_hertz_isSet;
    bool m_sample_rate_hertz_isValid;
    
    OAINumber speaking_rate;
    bool m_speaking_rate_isSet;
    bool m_speaking_rate_isValid;
    
    OAINumber pitch;
    bool m_pitch_isSet;
    bool m_pitch_isValid;
    
    OAINumber volume_gain_db;
    bool m_volume_gain_db_isSet;
    bool m_volume_gain_db_isValid;
    
    };

}

#endif // OAITTSAudioConfig_H
