/**
 * Farsava API
 * Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: amir@amerandish.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIVoiceSelectionParams.h
 *
 * The desired voice of the synthesized audio.
 */

#ifndef OAIVoiceSelectionParams_H
#define OAIVoiceSelectionParams_H

#include <QJsonObject>


#include "farsava_model/OAILanguageCode.h"
#include "farsava_model/OAITTSVoiceGender.h"
#include <QString>

#include "OAIObject.h"
#include "OAIEnum.h"

namespace Farsava {

class OAIVoiceSelectionParams: public OAIObject {
public:
    OAIVoiceSelectionParams();
    OAIVoiceSelectionParams(QString json);
    ~OAIVoiceSelectionParams() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    QString getVoiceId() const;
    void setVoiceId(const QString &voice_id);

    
    OAILanguageCode getLanguageCode() const;
    void setLanguageCode(const OAILanguageCode &language_code);

    
    QString getName() const;
    void setName(const QString &name);

    
    OAITTSVoiceGender getGender() const;
    void setGender(const OAITTSVoiceGender &gender);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    QString voice_id;
    bool m_voice_id_isSet;
    bool m_voice_id_isValid;
    
    OAILanguageCode language_code;
    bool m_language_code_isSet;
    bool m_language_code_isValid;
    
    QString name;
    bool m_name_isSet;
    bool m_name_isValid;
    
    OAITTSVoiceGender gender;
    bool m_gender_isSet;
    bool m_gender_isValid;
    
    };

}

#endif // OAIVoiceSelectionParams_H
